language: python

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y shellcheck

install:
    - pip install vim-vint

before_script: |
    git clone https://github.com/junegunn/vader.vim.git

script:
    - git ls-files | grep '.vim$' | xargs vint
    - git ls-files | grep '.sh$' | xargs shellcheck
    - ./test/run-tests.sh
